# Workspace clippy configuration. See: https://doc.rust-lang.org/clippy/configuration.html
allow-expect-in-tests          = true
allow-unwrap-in-tests          = true
cognitive-complexity-threshold = 25
too-many-arguments-threshold   = 9
type-complexity-threshold      = 250
